Update SLMN.GG to use Vue 3 with all the consequences that come from that
slmnio/slmngg-sfc pull request #224
Opened 2024-04-25 22:09 UTC by zusorio

2024-04-25 22:12 UTC, slmnio commented
Vue 3 features

- [ ] Fully refactor utils/dashboard.js to remove all passed auth objects
- [ ] Logged in user dropdown is still being annoying
- [ ] Check all Bootstrap components are working with the new package
- [ ] Move fully to vue 3 off the compat build

2.0 features

- [ ] Data server should needs to full load tables from time to time
- [ ] SLMN.GG Learn needs to be fully complete

2024-04-26 06:28 UTC, slmnio commented
Bunch of rules disabled because they were annoying but is probably worth enabling at some point for code quality

- typescript-eslint/no-floating-promises
- typescript-eslint/no-misused-promises
- typescript-eslint/no-implied-eval

2024-04-26 06:31 UTC, slmnio requested changes
Couple bits I found that got stuck in the linter

2024-04-26 06:31 UTC, slmnio commented on website/src/components/broadcast/Squeezable.vue
>              const small = this.$slots.default?.[0]?.elm;
From rule `vue/require-slots-as-functions` - need to look this up and fix it

2024-04-26 06:31 UTC, slmnio commented on website/src/components/broadcast/TeamAudio.vue
>                      delete this.lastPacketTime[user];
From rule `typescript-eslint/no-dynamic-delete`
This is from your audio stuff @zusorio, see if there's nice ways of unsetting without using delete

2024-04-26 06:31 UTC, slmnio commented on website/src/views/sub-views/PlayerMain.vue
>                      delete groups[key];
From rule `typescript-eslint/no-dynamic-delete`
I think this is easy, just requires filtering further later

2024-04-28 13:45 UTC, slmnio commented on website/src/components/broadcast/break/BreakOverlay.vue
> +.event-theme-border {
My editor is definitely going to indent this again lol

2024-04-28 13:49 UTC, zusorio commented on website/src/components/broadcast/break/BreakOverlay.vue
> +.event-theme-border {
I should probably figure out why my editor is not doing it

2024-04-28 13:50 UTC, slmnio commented on website/src/components/broadcast/break/BreakOverlay.vue
> +.event-theme-border {
I had to force it, similar with tbody/thead indenting

2024-05-01 21:08 UTC, slmnio approved these changes
Holy send

2024-05-01 21:08 UTC, slmnio approved these changes

2024-05-02 12:16 UTC, zusorio commented
Now tracked in #226

2024-05-02 12:16 UTC, closed without merging