Add tally lights overlay powered by obs scene changes
slmnio/slmngg-sfc pull request #89
Opened 2022-01-08 20:38 UTC by ZusorCode

- This adds a tally light system based on the OBS browser bindings
- Inside OBS a browser source with the url `/client/<clientname>/tally-transmitter` is added to scene of the corresponding observer's feed
- A viewer of the tally light visits `/client/<clientname>/tally-viewer`
- When the scene changes the OBS browser source notifies subscribed clients about the change

https://user-images.githubusercontent.com/23165606/148659135-db09be25-c833-4186-b501-d8d5ec92adcf.mp4

2022-01-09 14:52 UTC, slmnio requested changes
https://user-images.githubusercontent.com/15251071/148687321-420f86fd-5eae-4eff-bf53-ccbbb46d71c4.mp4

I've had some weird things with the scene name, but I think I know why:

1. The tally transmitter doesn't update every time the transmitting OBS changes scenes, so it might not be accurate whilst the feed is inactive
2. There's a race condition? (more of just logic the wrong way around) The `activeScene` changes _after_ the root detects a change with `active`. That means it's probably always sending an old scene name (unless there's a race condition between two listeners firing). https://github.com/slmnio/slmngg-sfc/blob/0981018afec7ec545b0b7d7af65a190c3c1abe5c/website/src/apps/BroadcastApp.vue#L45-L49 

You could probably get the correct scene name before you transmit you use `.transmitState` - and to be honest could track it locally in the transmitter rather than using the root's. That way you could probably also use other OBS APIs to keep the scenes up to date regardless of the transmitter source being active.

2022-01-09 22:36 UTC, slmnio commented on website/src/components/broadcast/roots/TallyTransmitter.vue
>              this.transmitState();
I don't actually think this will fix the race condition, it's gonna transmit before the callback of `.getCurrentScene` sets the local scene.  Maybe transmitting it inside the callback (with like a window.obsstudio null check so it'll send it if no OBS object)

2022-01-09 22:37 UTC, slmnio commented
To be honest I wonder what use case you're thinking of for the scenes - because that's the only thing that's not quite working properly. We can always take the branch with the scenes hidden for now for testing then bring it back after

2022-01-09 22:46 UTC, slmnio commented on website/src/components/broadcast/roots/TallyTransmitter.vue
> +    }
I think this should do it?
```suggestion
    methods: {
        transmit() {
            this.$socket.client.emit("tally_change", { clientName: this.client.key, state: this.state, sceneName: this.scene });
        },
        transmitState() {
            if (window.obsstudio) {
                window.obsstudio.getCurrentScene((scene) => {
                    this.scene = scene?.name;
                    this.transmit();
                });
            } else {
                this.transmit();
            }
        }
    },
    mounted() {
        window.addEventListener("obsSourceActiveChanged", (e) => {
            if (!this.client) return;
            this.active = e.detail.active;
            this.transmitState();
        });

        window.addEventListener("obsSourceVisibleChanged", (e) => {
            if (!this.client) return;
            this.visible = e.detail.visible;
            this.transmitState();
        });
    }
```

2022-01-09 22:46 UTC, slmnio commented on website/src/components/broadcast/roots/TallyTransmitter.vue
> +    }
I wish the diff was a bit more helpful - basically moving the function calls into one method so it can check for the OBS object, and either wait for the scene name or just transmit.

2022-01-09 22:54 UTC, slmnio commented
I think the only other thing to make it feel more intuitive is using some other listener to constantly update whatever the scene that's live is

2022-01-10 02:45 UTC, ZusorCode commented
Honestly the scenes thing was just an idea cap had, we can leave it out

2022-01-10 03:41 UTC, slmnio approved these changes

2022-01-10 03:42 UTC, slmnio commented
Sounds good, we can play with it later.

2022-01-10 03:44 UTC, merged