Add Player History Scene
slmnio/slmngg-sfc pull request #92
Opened 2022-01-13 04:38 UTC by JJ1898

Add a scene that displays a player's career history, potentially expandable to display things such as favorite hero or career win percentage

2022-01-14 05:51 UTC, slmnio requested changes
Some little things to clean up but it otherwise looks good. Might be worth posting your screenshot with a hero image in here too.

2022-01-14 05:51 UTC, slmnio commented on website/src/components/broadcast/PlayerHero.vue
> +        },
You should use the actual OW icons for this. You can import it from `content-utils` here: https://github.com/slmnio/slmngg-sfc/blob/8fbafb13a04c568429c6c51c1bbd247bd384568b/website/src/utils/content-utils.js#L106-L161

2022-01-14 05:51 UTC, slmnio commented on website/src/components/broadcast/PlayerHero.vue
> +    <div class="hero-portrait d-flex flex-row flex-center"><img :src="heroPortraitURL"/></div>
You'd want something here if there's no image so you don't get the dead image icon.

```suggestion
    <div class="hero-portrait d-flex flex-row flex-center"><img v-if="heroPortraitURL" :src="heroPortraitURL"/></div>
```
Might work if you want to keep the side space (though empty). Otherwise you could have the `v-if` on the `hero-portrait` itself.

To be fair, the likelihood of having a Hero that doesn't have an image is low, but not impossible.

2022-01-14 05:51 UTC, slmnio commented on website/src/components/broadcast/PlayerHero.vue
> +        },
Can be simplified. You don't even need the `|| null` really, it will just force anything falsy to be `null` instead.
```suggestion
        heroName() {
            return this.hero?.name || null;
        },
```

2022-01-14 05:51 UTC, slmnio commented on website/src/components/broadcast/PlayerHero.vue
> +        }
Did you know you can use optional chaining with square brackets? I didn't until recently. It looks really dumb: `?.[0]`. There's a helper function somewhere that deals with Airtable images but to be honest I don't care too much for it.

```suggestion
        heroPortraitURL() {
            return this.hero?.main_image?.[0]?.url;
        }
```

2022-01-18 00:35 UTC, JJ1898 commented on website/src/components/broadcast/PlayerHero.vue
> +        },
implemented in 373a8fb and 14ddda9

2022-01-18 00:35 UTC, JJ1898 commented on website/src/components/broadcast/PlayerHero.vue
> +        },
done in af0f00d

2022-01-18 00:37 UTC, JJ1898 commented on website/src/components/broadcast/PlayerHero.vue
> +    <div class="hero-portrait d-flex flex-row flex-center"><img :src="heroPortraitURL"/></div>
done here af0f00d

2022-01-18 00:38 UTC, JJ1898 commented on website/src/components/broadcast/PlayerHero.vue
> +        }
logic changes in here 8a1a202

2022-01-18 00:42 UTC, JJ1898 commented
Here's how the scene looks like as of 758f527
![image](https://user-images.githubusercontent.com/19962980/149851626-69d6f101-1425-4bc3-9313-dc6a2904e528.png)
styling for edge case teams is still needed

2022-01-18 20:26 UTC, slmnio approved these changes

2022-01-18 20:26 UTC, slmnio commented
![image](https://user-images.githubusercontent.com/15251071/150013235-e0938561-c466-48f5-aa29-177e4b62f1cf.png)

2022-01-18 20:26 UTC, merged